# Site settings
title: ONLYDEL
email: onlydel@wrw.kr
description: 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://onlydel.github.io" # the base hostname & protocol for your site
homeurl: "http://www.realgrid.com"
demourl: "http://demo.realgrid.com"
twitter_username: 
github_username: onlydel

# Build settings
markdown: kramdown

# Collections
category_list:
  - ASP.NET
  - EF
  - Visual Studio
  - Another Code
  - Javascript